[connections.mysql]
dialect = "mysql"
host = "test.c168egs2mcyz.ap-south-1.rds.amazonaws.com"
port = 3306
database = "scrum_board_stories"
username = "admin"
password = "tamali2807"
query = { charset = "utf8mb4" }
